name: hydroviz
description: "A hydrological visualization and modeling interface"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4  # Using the newer SDK version from main

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Core Dependencies
  cupertino_icons: ^1.0.8  # Updated to latest version
  provider: ^6.1.1         # State management
  drag_and_drop_lists: ^0.3.3
  vector_math: ^2.1.4
  
  # Networking and Utils
  http: ^1.1.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0   # Updated to latest version
  mockito: ^5.4.4         # Testing utilities

flutter:
  uses-material-design: true

  assets:
    - lib/assets/hydrovizlogo.png
    - lib/assets/profile.png
    - lib/assets/womp_womp.png