# Generated by Django 5.1.3 on 2024-11-19 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DRAFT', 'Draft')], max_length=20)),
                ('model_type', models.CharField(max_length=20)),
                ('metadata', models.JSONField(blank=True, help_text='Additional project metadata and settings', null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for project categorization', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AquiferProperties',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('layer_id', models.IntegerField()),
                ('conductivity_x', models.FloatField()),
                ('conductivity_y', models.FloatField()),
                ('conductivity_z', models.FloatField()),
                ('storage_coeff', models.FloatField()),
                ('porosity', models.FloatField()),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('effective_depth', models.FloatField(blank=True, help_text='Effective depth of the aquifer layer', null=True)),
                ('anisotropy_ratio', models.FloatField(blank=True, help_text='Ratio of horizontal to vertical conductivity', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquifer_properties', to='hydro_sim.project')),
            ],
            options={
                'verbose_name_plural': 'Aquifer Properties',
            },
        ),
        migrations.CreateModel(
            name='SimulationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mesh_data', models.JSONField(blank=True, null=True)),
                ('boundary_conditions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation_type', models.CharField(choices=[('STEADY_STATE', 'Steady State'), ('TRANSIENT', 'Transient'), ('PARTICLE_TRACKING', 'Particle Tracking')], default='STEADY_STATE', max_length=50)),
                ('convergence_criteria', models.JSONField(blank=True, help_text='Convergence criteria for the simulation', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='hydro_sim.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_step', models.IntegerField()),
                ('result_data', models.JSONField()),
                ('location_x', models.FloatField(null=True)),
                ('location_y', models.FloatField(null=True)),
                ('layer_id', models.IntegerField(null=True)),
                ('head_value', models.FloatField(null=True)),
                ('flow_rate', models.FloatField(null=True)),
                ('convergence', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hydro_sim.simulationmodel')),
            ],
            options={
                'ordering': ['time_step'],
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('well_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('ground_elevation', models.FloatField()),
                ('total_depth', models.FloatField()),
                ('install_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('purpose', models.CharField(max_length=50)),
                ('screen_bottom', models.FloatField(blank=True, help_text='Bottom of well screen elevation', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional well metadata', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='hydro_sim.project')),
            ],
        ),
        migrations.CreateModel(
            name='FieldMeasurement',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('measure_date', models.DateTimeField()),
                ('water_level', models.FloatField()),
                ('temperature', models.FloatField()),
                ('conductivity', models.FloatField()),
                ('quality', models.CharField(max_length=20)),
                ('measured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='hydro_sim.well')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'created_date'], name='hydro_sim_p_status_726c84_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'status'], name='hydro_sim_p_owner_i_7c5d66_idx'),
        ),
        migrations.AddIndex(
            model_name='aquiferproperties',
            index=models.Index(fields=['project', 'layer_id'], name='hydro_sim_a_project_e69af6_idx'),
        ),
        migrations.AddIndex(
            model_name='aquiferproperties',
            index=models.Index(fields=['location_x', 'location_y'], name='hydro_sim_a_locatio_973cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationmodel',
            index=models.Index(fields=['project', 'created_at'], name='hydro_sim_s_project_5f5b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationresult',
            index=models.Index(fields=['model', 'time_step'], name='hydro_sim_s_model_i_d5be4c_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationresult',
            index=models.Index(fields=['status', 'created_at'], name='hydro_sim_s_status_b0ae58_idx'),
        ),
        migrations.AddIndex(
            model_name='well',
            index=models.Index(fields=['project', 'status'], name='hydro_sim_w_project_792cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='well',
            index=models.Index(fields=['location_x', 'location_y'], name='hydro_sim_w_locatio_43e32a_idx'),
        ),
    ]
